version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    image: chat-app-backend:latest
    depends_on:
      db:
        condition: service_healthy  # Wait until db is healthy
    environment:
      spring.data.mongodb.uri: mongodb://db:27017/chatapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
